### ISSUE TITLE
nickname i18n using a variation of punycode

### ISSUE THREAD

**Issue by sdaugherty** [ircv3/ircv3-ideas#2] opened 2016-07-28 08:00 UTC
Was thinking about internationalization and nicknames, and thought about a possible scheme to implement nickname internationalization in a way that does not break clients or servers, nor does it
invite abuse.

Internationalized nicknames could be represented in ASCII using a variation on Punycode (which is used for internationalization of domain names).

The ASCII representation would be used for all IRC commands, and it would be recommended for clients to show and accept both the "proper" UTF-8 representation and the ASCII representation.

Thoughts?

**Comment by sdaugherty** [comment] 2016-07-28 08:18
Zarthus points out that [RFC7700](https://tools.ietf.org/html/rfc7700) covers exactly this,, however, some implementation details specific to IRC probably need to be spelled out so as not to enable abuse.

Specifically, it must always be possible for a user who can only input characters in an ASCII character set to quickly and unambiguously issue commands that require the user's full nickname. (/kick. /whois, etc)

**Comment by jwheare** [comment] 2016-07-28 10:15
Dupe of ircv3/ircv3-specifications#259

**Closed as completed by jwheare** 2016-07-28 10:15 UTC
